### ISSUE TITLE
Final value in model.predict?

### ISSUE THREAD

**Issue by lambolambert** [lamres/hmm_market_behavior#1]
on line 35 of hmm_market_behavior_handle_data_catalyst.py, you take the final value from the array. Why is this? would mode of the array or even predict_proba and select max index be the best?

state = int(context.model.predict(features[context.cols_features].dropna())[-1])

**Comment by lambolambert** [comment]
as far as I can tell you are just selecting the value from the last col aka 'volume_deviation'

**Comment by lamres** [comment]
You should get the last value, because model.predict(...) returns the list of predictions. The length of this list is the number of rows in a dataset. We are interested in the current hidden state, then you should take the last one.

**Comment by lambolambert** [comment]
from the documentation: https://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn.base._BaseHMM.predict

Parameters: | X (array-like, shape (n_samples, n_features)) – Feature matrix of individual samples.lengths (array-like of integers, shape (n_sequences, ), optional) – Lengths of the individual sequences in X. The sum of these should be n_samples.
-- | --
state_sequence – Labels for each sample from X.
array, shape (n_samples, )

does this suggest that its not the current hidden state? 
Just trying to understand it more as its some great stuff you have put out here

**Comment by lamres** [comment]
In my case, model.predict(...) returns the list like this:
[1 0 0 0 0 0]

It represents the hidden state for each sample (row) in the input dataframe. The list contains 6 values because 6 is the number of rows in the dataframe after dropna().
